### ISSUE TITLE
博客迁移成功了捏-----从wordpress 2 hexo - DrYexiuの随手记

### ISSUE THREAD

**Issue by AyaneYe** [AyaneYe/FW-Blog#1]
https://drbstore.han-han.xyz/2021/12/25/21-12-25/ 

 上周原本打算登blog写个年度总结来着，然后突然发现进不去wp的后台了，倒腾一通发现是那个拉跨的面板服务器问题（还没法导入HTTPS证书，导致有时候出一些奇怪的问题），就索性直接改用Hexo + Github Pages了。折腾了好几天 从入门到放弃 ，总算装修的差不多了顺带感谢 憨憨大佬 愿意教咱这个fw（（（

**Comment by DrMengBao** [comment]
好耶~（我复活了）
